schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_id:
          type: string
          description: "VPC ID"
        ami_id:
          type: string
          description: "AMI ID for ecs/ec2 instances"
        ssh_key_name:
          type: string
          description: "SSH Key Name"
        subnet_id_one:
          type: string
          description: "Subnet ID for subnet one"
        subnet_id_two:
          type: string
          description: "Subnet ID for subnet Two"
